version: '2'
services:
  dockerdind_{OID}:
    image: "flowq/dind"
    tty: true
    privileged: true
    hostname:  "cloud_node01"
    networks:
     - {OID}
    volumes:
     - share:/data/share:ro
     - {OID}:/data/work

networks:
 {OID}:
    driver: overlay
