version: '2'
services:
  git_{OID}:
    image: "flowq/git"
    tty: true
    cpu_shares: 0.5
    cpu_rt_period:  '500000'
    mem_limit: '64m'
    networks:
     - {OID}
    volumes:
     - share:/data/share:ro
     - {OID}:/data/work


networks:
 {OID}:
    driver: overlay
